# Generated by Django 5.0 on 2023-12-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproj', '0004_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(),
        ),
    ]
