# Generated by Django 5.0 on 2023-12-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproj', '0005_alter_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
