# Generated by Django 5.0 on 2024-01-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproj', '0008_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Footwear'},
        ),
    ]
