# Generated by Django 5.0 on 2024-01-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproj', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
    ]
